export const RECEIVE_PRODUCT = 'RECEIVE_PAGE';
export const REQUEST_PRODUCT = 'REQUEST_PAGE';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const UNSELECT_PRODUCT = 'UNSELECT_PRODUCT';
export const UNSELECT_ALL_PRODUCTS = 'UNSELECT_ALL_PRODUCTS';